name: CI Pipeline

on:
  push:

jobs:
  run-ci-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run CI Script
        run: echo "CI Pipeline Executed Successfully"

